POST http://127.0.0.1:8000/account/login_api/
Content-Type: application/json

{ "username": "test22", "password": "pass2003!" }

###

POST http://127.0.0.1:8000/account/register_api/
Content-Type: application/json

{ "username": "test22", "password": "pass2003!", "email": "testemail@gmail.com" }

###

GET http://127.0.0.1:8000/account/test_token/
Content-Type: application/json
Authorization: Token 868f8dc683d13e5b154d336a84b1c8bae4d97f88

{}
